# Generated by Django 6.0 on 2025-12-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('courseCode', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
    ]
